language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
services:
  - redis-server
  - mysql
env:
  - CODECOV_TOKEN="44a19034-f133-45e2-89ae-fb07901f29d8"
before_install:
  - npm install -g codecov
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'SET NAMES utf8mb4;'
  - mysql -e 'SET FOREIGN_KEY_CHECKS = 0;'
  - mysql -e 'USE test; DROP TABLE IF EXISTS `book`;'
  - mysql -e 'USE test; CREATE TABLE `book` (`book_id` int(10) unsigned NOT NULL AUTO_INCREMENT,`book_title` varchar(255) DEFAULT NULL,`book_anthor` varchar(255) DEFAULT NULL,`book_desc` varchar(255) DEFAULT NULL,PRIMARY KEY (`book_id`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;'
  - mysql -e 'BEGIN;'
  - mysql -e 'USE test;INSERT INTO `book` VALUES (1, "C#开发指南", "ken", "一本关于C#语言开发的书");'
  - mysql -e 'USE test;INSERT INTO `book` VALUES (2, "Java开发指南", "ben", "一本关于Java语言开发的书");'
  - mysql -e 'USE test;INSERT INTO `book` VALUES (3, "PHP开发指南", "ben", "一本关于PHP语言开发的书");'
  - mysql -e 'COMMIT;'
  - mysql -e 'SET FOREIGN_KEY_CHECKS = 1;'
script:
  - "npm run test"
  - "npm run report-coverage"
